/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.PersonInformation;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Name
 */
public class UserInputJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserInputJPanel
     */
    private final PersonInformation personInformation;
    
    public UserInputJPanel(PersonInformation personInformation) {
        initComponents();
        this.personInformation = personInformation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNamejLabel = new javax.swing.JLabel();
        generalInformationjLabel = new javax.swing.JLabel();
        generalInformationjSeparator = new javax.swing.JSeparator();
        firstNamejLabel = new javax.swing.JLabel();
        firstNameTextField = new java.awt.TextField();
        lastNameTextField = new java.awt.TextField();
        lastNamejLabel = new javax.swing.JLabel();
        phoneNumberTextField = new java.awt.TextField();
        phoneNumberjLabel = new javax.swing.JLabel();
        ssnjLabel = new javax.swing.JLabel();
        ssnTextField = new java.awt.TextField();
        dobTextField = new java.awt.TextField();
        DoBjLabel = new javax.swing.JLabel();
        ageTextField = new java.awt.TextField();
        agejLabel = new javax.swing.JLabel();
        addressInformationjLabel = new javax.swing.JLabel();
        addressInformationjSeparator = new javax.swing.JSeparator();
        streetAddressTextField = new java.awt.TextField();
        streetAddressjLabel1 = new javax.swing.JLabel();
        stateTextField = new java.awt.TextField();
        statejLabel = new javax.swing.JLabel();
        cityjLabel1 = new javax.swing.JLabel();
        cityTextField = new java.awt.TextField();
        zipCodeTextField = new java.awt.TextField();
        zipCodejLabel = new javax.swing.JLabel();
        routingNumberjLabel = new javax.swing.JLabel();
        bankAccountInformationjLabel = new javax.swing.JLabel();
        bankAccountInformationjSeparator = new javax.swing.JSeparator();
        bankNamejLabel = new javax.swing.JLabel();
        bankNamejTextField = new java.awt.TextField();
        accountTypejLabel = new javax.swing.JLabel();
        accountBalancejTextField = new java.awt.TextField();
        accountBalancejLabel = new javax.swing.JLabel();
        accountNumberjLabel = new javax.swing.JLabel();
        accountNumberjTextField = new java.awt.TextField();
        routingNumberjTextField = new java.awt.TextField();
        accountTypejComboBox = new javax.swing.JComboBox<>();
        driverLicenseInformationjLabel = new javax.swing.JLabel();
        driverLicenseInformationjSeparator = new javax.swing.JSeparator();
        licenseNumberjLabel = new javax.swing.JLabel();
        licenseNumberTextField = new java.awt.TextField();
        dateOfIssuejTextField = new java.awt.TextField();
        dateOfIssuejLabel = new javax.swing.JLabel();
        dateOfExpirationjTextField = new java.awt.TextField();
        dateOfExpirationjLabel2 = new javax.swing.JLabel();
        bloodTypejLabel = new javax.swing.JLabel();
        bloodTypejComboBox = new javax.swing.JComboBox<>();
        medicalRecordInformationjLabel = new javax.swing.JLabel();
        medicalRecordInformationjSeparator = new javax.swing.JSeparator();
        medicalRecordNumberjTextField = new java.awt.TextField();
        medicalRecordNumberjLabel = new javax.swing.JLabel();
        alergy3jLabel = new javax.swing.JLabel();
        alergy2jTextField = new java.awt.TextField();
        alergy2jLabel = new javax.swing.JLabel();
        alergy1jLabel = new javax.swing.JLabel();
        alergy1jTextField = new java.awt.TextField();
        alergy3jTextField = new java.awt.TextField();
        saveInformation = new javax.swing.JButton();
        heightLabel = new javax.swing.JLabel();
        heightTextField = new java.awt.TextField();
        weightTextField = new java.awt.TextField();
        weightLabel = new javax.swing.JLabel();
        routingNumberjLabel1 = new javax.swing.JLabel();
        bankNamejLabel1 = new javax.swing.JLabel();
        bankNameCheckingjTextField = new java.awt.TextField();
        accountTypejLabel1 = new javax.swing.JLabel();
        accountBalanceCheckingjTextField = new java.awt.TextField();
        accountBalancejLabel1 = new javax.swing.JLabel();
        accountNumberjLabel1 = new javax.swing.JLabel();
        accountNumberCheckingjTextField = new java.awt.TextField();
        routingNumberCheckingjTextField = new java.awt.TextField();
        accountTypeCheckingjComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        licenseNumberjLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        panelNamejLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        panelNamejLabel.setText("Create User Profile");

        generalInformationjLabel.setText("General Information");

        generalInformationjSeparator.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        firstNamejLabel.setText("First Name:");

        firstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNamejLabel.setText("Last Name:");

        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        phoneNumberjLabel.setText("Phone #:");

        ssnjLabel.setText("SSN:");

        DoBjLabel.setText("Date Of Birth:");

        agejLabel.setText("Age:");

        addressInformationjLabel.setText("Address Information");

        addressInformationjSeparator.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        streetAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetAddressTextFieldActionPerformed(evt);
            }
        });

        streetAddressjLabel1.setText("Street Address:");

        statejLabel.setText("State:");

        cityjLabel1.setText("City:");

        zipCodejLabel.setText("Zip Code:");

        routingNumberjLabel.setText("Routing #:");

        bankAccountInformationjLabel.setText("Bank Account Information");

        bankAccountInformationjSeparator.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        bankNamejLabel.setText("Bank Name:");

        bankNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNamejTextFieldActionPerformed(evt);
            }
        });

        accountTypejLabel.setText("Account Type:");

        accountBalancejLabel.setText("Account Balance:");

        accountNumberjLabel.setText("Account #:");

        accountTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings Account" }));
        accountTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypejComboBoxActionPerformed(evt);
            }
        });

        driverLicenseInformationjLabel.setText("Driver License Information");

        driverLicenseInformationjSeparator.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        licenseNumberjLabel.setText("License #:");

        licenseNumberTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        licenseNumberTextField.setForeground(new java.awt.Color(0, 0, 0));
        licenseNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberTextFieldActionPerformed(evt);
            }
        });

        dateOfIssuejLabel.setText("Date Of Issue:");

        dateOfExpirationjLabel2.setText("Date Of Expiration:");

        bloodTypejLabel.setText("Blood Type:");

        bloodTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bloodTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypejComboBoxActionPerformed(evt);
            }
        });

        medicalRecordInformationjLabel.setText("Medical Record Information");

        medicalRecordInformationjSeparator.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        medicalRecordNumberjLabel.setText("Medical Record #:");

        alergy3jLabel.setText("Alergy 3:");

        alergy2jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy2jTextFieldActionPerformed(evt);
            }
        });

        alergy2jLabel.setText("Alergy 2:");

        alergy1jLabel.setText("Alergy 1:");

        saveInformation.setBackground(new java.awt.Color(255, 153, 153));
        saveInformation.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        saveInformation.setText("Save Information");
        saveInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInformationActionPerformed(evt);
            }
        });

        heightLabel.setText("Height:");

        weightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightTextFieldActionPerformed(evt);
            }
        });

        weightLabel.setText("Weight:");

        routingNumberjLabel1.setText("Routing #:");

        bankNamejLabel1.setText("Bank Name:");

        accountTypejLabel1.setText("Account Type:");

        accountBalancejLabel1.setText("Account Balance:");

        accountNumberjLabel1.setText("Account #:");

        accountTypeCheckingjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking Account" }));
        accountTypeCheckingjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeCheckingjComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Browse Picture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        licenseNumberjLabel1.setText("Uploade photo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bankAccountInformationjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankAccountInformationjSeparator)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(driverLicenseInformationjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driverLicenseInformationjSeparator)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressInformationjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressInformationjSeparator))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(streetAddressjLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cityjLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statejLabel)
                                .addGap(18, 18, 18)
                                .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipCodejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generalInformationjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generalInformationjSeparator))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(routingNumberjLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(heightLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ssnjLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(firstNamejLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DoBjLabel)
                                            .addComponent(lastNamejLabel)
                                            .addComponent(weightLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(phoneNumberjLabel)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(agejLabel)
                                                        .addGap(43, 43, 43)
                                                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(panelNamejLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bankNamejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bankNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(accountNumberjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(accountNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(accountBalancejLabel)
                                .addGap(10, 10, 10)
                                .addComponent(accountBalancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(medicalRecordInformationjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicalRecordInformationjSeparator))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(372, 372, 372)
                                .addComponent(saveInformation))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medicalRecordNumberjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(medicalRecordNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alergy1jLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alergy1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alergy2jLabel)
                                .addGap(10, 10, 10)
                                .addComponent(alergy2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alergy3jLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alergy3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(routingNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bankNamejLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(routingNumberCheckingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bankNameCheckingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(routingNumberjLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accountTypejLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountTypeCheckingjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accountNumberjLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountNumberCheckingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountBalancejLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(accountBalanceCheckingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accountTypejLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(licenseNumberjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(licenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateOfIssuejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateOfIssuejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateOfExpirationjLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateOfExpirationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bloodTypejLabel)
                                .addGap(18, 18, 18)
                                .addComponent(bloodTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(licenseNumberjLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNamejLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generalInformationjLabel)
                    .addComponent(generalInformationjSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNamejLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNamejLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberjLabel)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssnjLabel)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoBjLabel)
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agejLabel)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heightLabel)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addressInformationjLabel)
                    .addComponent(addressInformationjSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetAddressjLabel1)
                    .addComponent(streetAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityjLabel1)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statejLabel)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodejLabel)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bankAccountInformationjLabel)
                    .addComponent(bankAccountInformationjSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankNamejLabel)
                    .addComponent(bankNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalancejLabel)
                    .addComponent(accountBalancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNumberjLabel)
                    .addComponent(accountNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routingNumberjLabel)
                            .addComponent(routingNumberjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountTypejLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankNamejLabel1)
                    .addComponent(bankNameCheckingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalancejLabel1)
                    .addComponent(accountBalanceCheckingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNumberjLabel1)
                    .addComponent(accountNumberCheckingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(routingNumberjLabel1)
                        .addComponent(routingNumberCheckingjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accountTypejLabel1)
                        .addComponent(accountTypeCheckingjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(driverLicenseInformationjLabel)
                    .addComponent(driverLicenseInformationjSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bloodTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodTypejLabel)
                    .addComponent(licenseNumberjLabel)
                    .addComponent(licenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfIssuejLabel)
                    .addComponent(dateOfIssuejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfExpirationjLabel2)
                    .addComponent(dateOfExpirationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNumberjLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medicalRecordInformationjLabel)
                    .addComponent(medicalRecordInformationjSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicalRecordNumberjLabel)
                    .addComponent(medicalRecordNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy1jLabel)
                    .addComponent(alergy1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy2jLabel)
                    .addComponent(alergy2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergy3jLabel)
                    .addComponent(alergy3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveInformation)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypejComboBoxActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void licenseNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberTextFieldActionPerformed

    private void bloodTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypejComboBoxActionPerformed

    private void alergy2jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy2jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy2jTextFieldActionPerformed

    private void saveInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInformationActionPerformed
        personInformation.getGeneralInformation().setFirstName(firstNameTextField.getText());
        personInformation.getGeneralInformation().setLastName(lastNameTextField.getText());
        personInformation.getGeneralInformation().setDateOfBirth(dobTextField.getText());
        
        personInformation.getAddressInformation().setStreetAddress(streetAddressTextField.getText());
        personInformation.getAddressInformation().setCityAddress(cityTextField.getText());
        personInformation.getAddressInformation().setStateAddress(stateTextField.getText());
        
        personInformation.getAccountInformation().setBankName(bankNamejTextField.getText());
        personInformation.getAccountInformation().setAccountType(accountTypejComboBox.getSelectedItem().toString());
        
        personInformation.getAccountInformation().setBankNameChecking(bankNameCheckingjTextField.getText());
        personInformation.getAccountInformation().setAccountTypeChecking(accountTypeCheckingjComboBox1.getSelectedItem().toString());
        
        personInformation.getLicenseInformation().setLicenseIssueDate(dateOfIssuejTextField.getText());
        personInformation.getLicenseInformation().setLicenseExpirationDate(dateOfExpirationjTextField.getText());
        personInformation.getLicenseInformation().setBloodGroup(bloodTypejComboBox.getSelectedItem().toString());
        
        personInformation.getMedicalInformation().setMedicalAlergy1(alergy1jTextField.getText());
        personInformation.getMedicalInformation().setMedicalAlergy2(alergy2jTextField.getText());
        personInformation.getMedicalInformation().setMedicalAlergy3(alergy3jTextField.getText());

        // Verify if all the inputs are numbers, display a warning otherwise
        try {
            personInformation.getGeneralInformation().setCurrentAge(Integer.parseInt(ageTextField.getText()));
            personInformation.getGeneralInformation().setPhoneNumber(Integer.parseInt(phoneNumberTextField.getText()));
            personInformation.getGeneralInformation().setSocialSecurityNumber(Integer.parseInt(ssnTextField.getText()));
            personInformation.getGeneralInformation().setHumanHeight(Integer.parseInt(heightTextField.getText()));
            personInformation.getGeneralInformation().setHumanWeight(Integer.parseInt(weightTextField.getText()));
            personInformation.getAddressInformation().setZipCode(Integer.parseInt(zipCodeTextField.getText()));
            personInformation.getAccountInformation().setAccountBalance(Integer.parseInt(accountBalancejTextField.getText()));
            personInformation.getAccountInformation().setAccountNumber(Integer.parseInt(accountNumberjTextField.getText()));
            personInformation.getAccountInformation().setRoutingNumber(Integer.parseInt(routingNumberjTextField.getText()));
            personInformation.getAccountInformation().setAccountBalanceChecking(Integer.parseInt(accountBalanceCheckingjTextField.getText()));
            personInformation.getAccountInformation().setAccountNumberChecking(Integer.parseInt(accountNumberCheckingjTextField.getText()));
            personInformation.getAccountInformation().setRoutingNumberChecking(Integer.parseInt(routingNumberCheckingjTextField.getText()));
            personInformation.getLicenseInformation().setLicenseNumber(Integer.parseInt(licenseNumberTextField.getText()));
            personInformation.getMedicalInformation().setRecordNumber(Integer.parseInt(medicalRecordNumberjTextField.getText()));
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(null, "Please input a number");
            return;
        }
        JOptionPane.showMessageDialog(null, "Profile Successfully Created");
    }//GEN-LAST:event_saveInformationActionPerformed

    private void streetAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetAddressTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void weightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightTextFieldActionPerformed

    private void accountTypeCheckingjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeCheckingjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeCheckingjComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            personInformation.getLicenseInformation().setProfilePicturePath(path);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void bankNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankNamejTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoBjLabel;
    private java.awt.TextField accountBalanceCheckingjTextField;
    private javax.swing.JLabel accountBalancejLabel;
    private javax.swing.JLabel accountBalancejLabel1;
    private java.awt.TextField accountBalancejTextField;
    private java.awt.TextField accountNumberCheckingjTextField;
    private javax.swing.JLabel accountNumberjLabel;
    private javax.swing.JLabel accountNumberjLabel1;
    private java.awt.TextField accountNumberjTextField;
    private javax.swing.JComboBox<String> accountTypeCheckingjComboBox1;
    private javax.swing.JComboBox<String> accountTypejComboBox;
    private javax.swing.JLabel accountTypejLabel;
    private javax.swing.JLabel accountTypejLabel1;
    private javax.swing.JLabel addressInformationjLabel;
    private javax.swing.JSeparator addressInformationjSeparator;
    private java.awt.TextField ageTextField;
    private javax.swing.JLabel agejLabel;
    private javax.swing.JLabel alergy1jLabel;
    private java.awt.TextField alergy1jTextField;
    private javax.swing.JLabel alergy2jLabel;
    private java.awt.TextField alergy2jTextField;
    private javax.swing.JLabel alergy3jLabel;
    private java.awt.TextField alergy3jTextField;
    private javax.swing.JLabel bankAccountInformationjLabel;
    private javax.swing.JSeparator bankAccountInformationjSeparator;
    private java.awt.TextField bankNameCheckingjTextField;
    private javax.swing.JLabel bankNamejLabel;
    private javax.swing.JLabel bankNamejLabel1;
    private java.awt.TextField bankNamejTextField;
    private javax.swing.JComboBox<String> bloodTypejComboBox;
    private javax.swing.JLabel bloodTypejLabel;
    private java.awt.TextField cityTextField;
    private javax.swing.JLabel cityjLabel1;
    private javax.swing.JLabel dateOfExpirationjLabel2;
    private java.awt.TextField dateOfExpirationjTextField;
    private javax.swing.JLabel dateOfIssuejLabel;
    private java.awt.TextField dateOfIssuejTextField;
    private java.awt.TextField dobTextField;
    private javax.swing.JLabel driverLicenseInformationjLabel;
    private javax.swing.JSeparator driverLicenseInformationjSeparator;
    private java.awt.TextField firstNameTextField;
    private javax.swing.JLabel firstNamejLabel;
    private javax.swing.JLabel generalInformationjLabel;
    private javax.swing.JSeparator generalInformationjSeparator;
    private javax.swing.JLabel heightLabel;
    private java.awt.TextField heightTextField;
    private javax.swing.JButton jButton1;
    private java.awt.TextField lastNameTextField;
    private javax.swing.JLabel lastNamejLabel;
    private java.awt.TextField licenseNumberTextField;
    private javax.swing.JLabel licenseNumberjLabel;
    private javax.swing.JLabel licenseNumberjLabel1;
    private javax.swing.JLabel medicalRecordInformationjLabel;
    private javax.swing.JSeparator medicalRecordInformationjSeparator;
    private javax.swing.JLabel medicalRecordNumberjLabel;
    private java.awt.TextField medicalRecordNumberjTextField;
    private javax.swing.JLabel panelNamejLabel;
    private java.awt.TextField phoneNumberTextField;
    private javax.swing.JLabel phoneNumberjLabel;
    private java.awt.TextField routingNumberCheckingjTextField;
    private javax.swing.JLabel routingNumberjLabel;
    private javax.swing.JLabel routingNumberjLabel1;
    private java.awt.TextField routingNumberjTextField;
    private javax.swing.JButton saveInformation;
    private java.awt.TextField ssnTextField;
    private javax.swing.JLabel ssnjLabel;
    private java.awt.TextField stateTextField;
    private javax.swing.JLabel statejLabel;
    private java.awt.TextField streetAddressTextField;
    private javax.swing.JLabel streetAddressjLabel1;
    private javax.swing.JLabel weightLabel;
    private java.awt.TextField weightTextField;
    private java.awt.TextField zipCodeTextField;
    private javax.swing.JLabel zipCodejLabel;
    // End of variables declaration//GEN-END:variables
}
